Use real size instead of multiples of 1024 for sizes
Exception: Size values in stats files are still in units of 1024 for
backward compatibility reasons.