blake3: fix build with compilers lacking Neon support
Add BLAKE3_NO_NEON_CHECK and set it if neon has not been detected.

The auto-detect in .h file has no way to add necessary files into
the cmake sources list, so it should just do what the cmake has
already figured out.

Fixes: https://github.com/sobomax/ccache/actions/runs/18319767214/job/52169608062#step:7:6477

 > [linux/arm64 build 13/18] RUN CMAKE_PARAMS="-DCMAKE_INSTALL_PREFIX=/usr   `./misc/get-arch-buildargs platformopts -DSTATIC_LINK=ON`" /source/ci/build:
1993.1 [ 96%] Building CXX object unittest/CMakeFiles/unittest.dir/test_util_zstd.cpp.o
2010.7 [ 97%] Building CXX object unittest/CMakeFiles/unittest.dir/testutil.cpp.o
2011.9 [ 98%] Building CXX object unittest/CMakeFiles/unittest.dir/test_inodecache.cpp.o
2065.8 [100%] Linking CXX executable unittest
: ../src/third_party/blake3/libdep_blake3.a(blake3_dispatch.c.o): in function `blake3_hash_many':
2068.5 blake3_dispatch.c:(.text+0x90): undefined reference to `blake3_hash_many_neon'
2068.9 collect2: error: ld returned 1 exit status