Use BLAKE3 machinery for detecting AVX2 support (#696)
* Use BLAKE3 machinery for detecting AVX2 support

Instead of relying on the sometimes broken __builtin_cpu_support. See
discussion in #689.

* Require GCC >= 5.0 to enable AVX2 support

On e.g. GCC 4.8.5 the build fails with:
error: ‘__m256i’ does not name a type